# Generated by Django 2.0 on 2020-03-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('psw', models.CharField(max_length=200)),
                ('remember', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.RenameField(
            model_name='query',
            old_name='comments',
            new_name='query',
        ),
    ]
