# Generated by Django 2.0 on 2020-03-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_login_remember'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('psw', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
