# Generated by Django 2.0 on 2020-03-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('userphone', models.CharField(max_length=200)),
                ('useremail', models.CharField(max_length=200)),
                ('usercity', models.CharField(max_length=200)),
                ('selectcar', models.CharField(max_length=200)),
                ('selectservice', models.CharField(max_length=200)),
                ('uservehcle', models.CharField(max_length=200)),
                ('preferdate', models.CharField(max_length=200)),
                ('prefertime', models.CharField(max_length=200)),
                ('call', models.CharField(max_length=200)),
                ('ohterInfo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'booking1',
            },
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
