# Generated by Django 2.0 on 2020-04-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20200425_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'detailing',
            },
        ),
    ]
