# Generated by Django 2.0 on 2020-04-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_blog1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
