# Generated by Django 2.0 on 2020-05-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking1',
            old_name='ohterInfo',
            new_name='otherInfo',
        ),
        migrations.RenameField(
            model_name='booking1',
            old_name='uservehcle',
            new_name='useraddress',
        ),
        migrations.AlterField(
            model_name='blog',
            name='detail',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog1',
            name='detail',
            field=models.CharField(max_length=2000),
        ),
    ]
