# Generated by Django 2.0 on 2020-05-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_auto_20200505_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
