# Generated by Django 2.0 on 2020-05-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='product',
            table='Ordering',
        ),
    ]
