# Generated by Django 2.0 on 2020-05-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_auto_20200518_1807'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
