# Generated by Django 2.0 on 2020-05-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_auto_20200518_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
