# Generated by Django 2.0 on 2020-05-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_auto_20200518_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
